# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from data_manager.gen import data_manager_pb2 as data__manager_dot_gen_dot_data__manager__pb2


class DataManagerStub(object):
    """The data manager service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTask = channel.unary_unary(
                '/DataManager/AddTask',
                request_serializer=data__manager_dot_gen_dot_data__manager__pb2.AddTaskReq.SerializeToString,
                response_deserializer=data__manager_dot_gen_dot_data__manager__pb2.AddTaskResp.FromString,
                )
        self.StartTask = channel.unary_unary(
                '/DataManager/StartTask',
                request_serializer=data__manager_dot_gen_dot_data__manager__pb2.StartTaskReq.SerializeToString,
                response_deserializer=data__manager_dot_gen_dot_data__manager__pb2.StartTaskResp.FromString,
                )
        self.StopTask = channel.unary_unary(
                '/DataManager/StopTask',
                request_serializer=data__manager_dot_gen_dot_data__manager__pb2.StopTaskReq.SerializeToString,
                response_deserializer=data__manager_dot_gen_dot_data__manager__pb2.StopTaskResp.FromString,
                )
        self.FinishTask = channel.unary_unary(
                '/DataManager/FinishTask',
                request_serializer=data__manager_dot_gen_dot_data__manager__pb2.FinishTaskReq.SerializeToString,
                response_deserializer=data__manager_dot_gen_dot_data__manager__pb2.FinishTaskResp.FromString,
                )
        self.GetTask = channel.unary_unary(
                '/DataManager/GetTask',
                request_serializer=data__manager_dot_gen_dot_data__manager__pb2.GetTaskReq.SerializeToString,
                response_deserializer=data__manager_dot_gen_dot_data__manager__pb2.GetTaskResp.FromString,
                )
        self.GetAllTasks = channel.unary_unary(
                '/DataManager/GetAllTasks',
                request_serializer=data__manager_dot_gen_dot_data__manager__pb2.GetAllTasksReq.SerializeToString,
                response_deserializer=data__manager_dot_gen_dot_data__manager__pb2.GetAllTasksResp.FromString,
                )
        self.UpdateTask = channel.unary_unary(
                '/DataManager/UpdateTask',
                request_serializer=data__manager_dot_gen_dot_data__manager__pb2.UpdateTaskReq.SerializeToString,
                response_deserializer=data__manager_dot_gen_dot_data__manager__pb2.UpdateTaskResp.FromString,
                )


class DataManagerServicer(object):
    """The data manager service definition.
    """

    def AddTask(self, request, context):
        """Add a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTask(self, request, context):
        """Start a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTask(self, request, context):
        """Stop a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishTask(self, request, context):
        """Will be called when a task finished
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Get task information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllTasks(self, request, context):
        """Get all tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTask(self, request, context):
        """Update task information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTask,
                    request_deserializer=data__manager_dot_gen_dot_data__manager__pb2.AddTaskReq.FromString,
                    response_serializer=data__manager_dot_gen_dot_data__manager__pb2.AddTaskResp.SerializeToString,
            ),
            'StartTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTask,
                    request_deserializer=data__manager_dot_gen_dot_data__manager__pb2.StartTaskReq.FromString,
                    response_serializer=data__manager_dot_gen_dot_data__manager__pb2.StartTaskResp.SerializeToString,
            ),
            'StopTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTask,
                    request_deserializer=data__manager_dot_gen_dot_data__manager__pb2.StopTaskReq.FromString,
                    response_serializer=data__manager_dot_gen_dot_data__manager__pb2.StopTaskResp.SerializeToString,
            ),
            'FinishTask': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishTask,
                    request_deserializer=data__manager_dot_gen_dot_data__manager__pb2.FinishTaskReq.FromString,
                    response_serializer=data__manager_dot_gen_dot_data__manager__pb2.FinishTaskResp.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=data__manager_dot_gen_dot_data__manager__pb2.GetTaskReq.FromString,
                    response_serializer=data__manager_dot_gen_dot_data__manager__pb2.GetTaskResp.SerializeToString,
            ),
            'GetAllTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTasks,
                    request_deserializer=data__manager_dot_gen_dot_data__manager__pb2.GetAllTasksReq.FromString,
                    response_serializer=data__manager_dot_gen_dot_data__manager__pb2.GetAllTasksResp.SerializeToString,
            ),
            'UpdateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTask,
                    request_deserializer=data__manager_dot_gen_dot_data__manager__pb2.UpdateTaskReq.FromString,
                    response_serializer=data__manager_dot_gen_dot_data__manager__pb2.UpdateTaskResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataManager(object):
    """The data manager service definition.
    """

    @staticmethod
    def AddTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataManager/AddTask',
            data__manager_dot_gen_dot_data__manager__pb2.AddTaskReq.SerializeToString,
            data__manager_dot_gen_dot_data__manager__pb2.AddTaskResp.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataManager/StartTask',
            data__manager_dot_gen_dot_data__manager__pb2.StartTaskReq.SerializeToString,
            data__manager_dot_gen_dot_data__manager__pb2.StartTaskResp.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataManager/StopTask',
            data__manager_dot_gen_dot_data__manager__pb2.StopTaskReq.SerializeToString,
            data__manager_dot_gen_dot_data__manager__pb2.StopTaskResp.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FinishTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataManager/FinishTask',
            data__manager_dot_gen_dot_data__manager__pb2.FinishTaskReq.SerializeToString,
            data__manager_dot_gen_dot_data__manager__pb2.FinishTaskResp.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataManager/GetTask',
            data__manager_dot_gen_dot_data__manager__pb2.GetTaskReq.SerializeToString,
            data__manager_dot_gen_dot_data__manager__pb2.GetTaskResp.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataManager/GetAllTasks',
            data__manager_dot_gen_dot_data__manager__pb2.GetAllTasksReq.SerializeToString,
            data__manager_dot_gen_dot_data__manager__pb2.GetAllTasksResp.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataManager/UpdateTask',
            data__manager_dot_gen_dot_data__manager__pb2.UpdateTaskReq.SerializeToString,
            data__manager_dot_gen_dot_data__manager__pb2.UpdateTaskResp.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
